name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar dependencias
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Configurar DVC remote
      - name: Setup DVC remote
        env:
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USER }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}

      # Hacer dvc pull
      - name: DVC Pull
        run: dvc pull -v

      # Correr pipeline
      - name: Run DVC pipeline
        run: dvc repro -v

      # Mostrar m√©tricas
      - name: Show metrics
        run: cat metrics.json